# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e66884057cd180ed93c4cd0bd47ed0d2f9bb2c7a57170a0b7b952c6d89aee808ded5e3b4491444c9c824df6dc31ef48f43a81ad205d87fda20d8f2212012005c

test:
  secret_key_base: 91e1458243f11d01d87dc1ad627a819d4d04f4635981c99341dfa9479f8c4c93639e028e571065280379b7478d32406c0c0566dd093d00ccb862e67a70b3d98b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
